# Generated by Django 5.2.7 on 2025-10-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='location',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='county',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='state',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='units',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
